robocup-junior/soccer-rules

- tex/rules.tex
changes rules so that gameplay continues when a robot is damaged. here, if two robots are damaged at kickoff, play is suspended. In effect, the team with robots must score an empty net goal
Changes what happens when two robots from the same team are broken - play resumes, so the other team must score a goal against an empty net. As before, if a team cannot field a team at kickoff, play is paused and one point is awarded every 30 seconds.
------
**Note**: The text is copy-pasted from #14 where this change was first introduced by @gngrbrdmn.
> update: Implement Sloan's proposed rule change

- tex/rules.tex
* Put the robot on the other side of the field after out of bounds has passed.
* Only put robots back when they are pushed out by a robot from another team.
> * Put the robot on the other side of the field after out of bounds has  passed.
It is quite difficult for the referee to remember where was a robot taken from. This gives them ability to put the robot "out of game" without having to remember where it was taken from.
> * Only put robots back when they are pushed out by a robot from another team.
This seems to have been a loophole in the rules, as it means that one robot may push another robot from the same team out of bounds and not be punished for doing that.
Restricting this rule to the robots of the opposing team should both make the rules a bit more fair and and the same time …
> out-of-bounds: A few changes

- tex/rules.tex
* Only the referee can move robots around.
* If multiple defense happens, move the robot on the other side of the field.
> * Only the referee can move robots around.
There seems to have been some confusion as to whether the referee or their assistant can more the robots in this situation. This change makes it referee only.
> * If multiple defense happens repeatedly, move the robot on the other side of the field.
This makes multiple defense to hurt a bit and also gives a reference point as to when should a robot be damaged for multiple defense.
> multiple-defense: A few updates

- tex/rules.tex
Add a note to the pre-match meeting section allowing the referee or their assistant to check whether  the robots are capable of playing.
In order to make sure damaged robots or robots that are not working are not allowed to enter the gameplay.
> pre-match meeting: Referee can check the robots

- tex/rules.tex
* Remove unnecessary parts
* Put robot on the other side of the field after the damage time has
passed.
* Add a note on reprogramming.
> * Remove unnecessary parts
This seems to be causing issues internationally (when the playing area is not inside the working area) and does not really seem to be necessary.
> * Put robot on the other side of the field after the damage time has
passed.
It is quite difficult for the referee to remember where was a robot taken from. This gives them ability to put the robot "out of game" without having to remember where it was taken from.
> * Add a note on reprogramming.
This causes some trouble when the kickoff does not start right away because the teams want to reprogram their robots. They may still do that, but only with explicit approval of the referee.
> damaged-robots: A few updates

- tex/rules.tex
* Add note on dribbler gears
* Add note on batteries
- Dribbler gears have a huge potential to harm both participants and also referees -- covering them is the least the participants can do to for everyone's safety.
- Swollen batteries are a disaster waiting to happen -- they should be banned, which is what this change does.
> update: Add safety updates

- tex/rules.tex
* Set countdown to three
Countdown at five has produced a lot of unnecessary waiting (see for instance the [discussion here](https://junior.forum.robocup.org/t/inspection-and-handling-of-lack-of-process-rule/693/6)) -- setting it at three should help.
> update: Set countdown to three

- rules.adoc
* Give more priority to the goalie inside the penalty area
* Ensure that breaking the goalie's priority inside the penalty area is
costly by moving the ball to the furthest unoccupied neutral spot.
* Minimize the amount of "sumo"-like gameplay that happens at RCJ Soccer.
> update: New rules for the penalty area

- rules.adoc
* Ensure the damaged robots section refers to robots moving to the penalty area instead of the goal.
* To better clarify the situation around the penalty vs. goal with regards to the new rules.
> update: `goal` -> `penalty area` in damaged robots

- rules.adoc
Clarified robot size requirement as being size of a cylinder the robot needs to fit
We had a team at RCJ European Championship show up with a 22cm square robot that they went through a newly established CJ tournament with. This indicates the previous formulation to be ambiguous as multiple teams and regional OC must have considered this a correct interpretation.
> Clarify robot size as needing to fit cylinder

- rules.adoc
Add "Smoothly" before "fit cylinder" in the dimension section. 
In past years, there're several interpretations for "fit" so sometimes even robot fits in the cylinder by force, it could be "fit". 
To avoid this difference in interpretations, this word should be in.
> "Smoothly" fit cylinder

- rules.adoc
Added language explicitly telling teams to be prepared for the ball to be different from what they would expect.
Tournament organizers might not be able to supply identical balls in all regions, therefore making coping with what will be available mandatory teams are warned to take variations into consideration.
> Advise teams to be prepared for deviations in golf ball parameters

- rules.adoc
Temporarily added banner on the top indicating this document as a draft and calling for feedback & participation on the forum
The draft rules is the most prominent and equitable place to invite participation and feedback on rule changes because most team members and mentors are likely to read it.
> Add prominent callout for public participation thread for draft rules

- preamble.tex
Updated 2023 draft rules with committee members as of 2022-08-01. Also title the list "Soccer League Committee" to make the title fit the document easily.
To be up to date and in line with the apparent new name of the committee.
> Update committee members with current (2022-08-01) committee

- rules.adoc
* Add a note on communication module provided by the OC to the teams as
part of the SuperTeam challenge.
* To make the SuperTeam games more manageable (especially from the organizational/referee perspective) and at the same time to foster inter-team collaboration and communication.
> Note on communication module for SuperTeams

- rules.adoc
Changed language around potential disqualification to always be "can be disqualified".
For consistency both inside the rules and with established practice.
> Made language around discqualification consistent to always be 'can be'

- rules.adoc
specify inside of goals to be colored yellow and blue and matte
That didn't got lost in the edit from 2020 to 2022 apparently
> Put specification of goals to be colored back in

- rules.adoc
Changed ball description to not refer to golf ball as hollow.
Golf balls unlike the previous passive balls are not hollow.
> Remove reference to golf ball as hollow

- rules.adoc
Clarify that robots are to be placed inside the goal for kicker test
It could currently be confusing whether the corner of the goal or of the field are being referred to.
> Clarify that robots are to be placed inside the goal for kicker test

- rules.adoc
removed reference to 2017 from only 2x in LWL rule
That the count starts at 2017 can no longer be relevant for any teams within the age limits.
> Cleanup of old transitional provisions

- preamble.tex
Moved 2022 committee members to "last year" spot and entered new ones.
To be up to date. Ideally I'd like to merge this and the updated field construction drawing into master simultaneously so we get only one revision of the rules.
> Updated for 2023 committee members

- superteam_rules.adoc
Put in a note that in the intl. competition we will only award 3:0 Byes in SuperTeam leagues
As discussed in the forum here: https://junior.forum.robocup.org/t/superteam-bye-reduced-to-3-0-soccer-rules-2024/3298
> Reduce SuperTeam Bye to 3:0

- rules.adoc
Added hint about magnetic field conditions probably being useless in Eindhoven
Experience from 2013 shows that relying on compass sensors is not really an option in the probable venue. This should only be merged after confirmation that it is going to be that same venue.
> hint about magnetic field conditions in Eindhoven

- rules.adoc
Add a rule regarding ball play: Robots must be able to approach and play a ball when it's placed on the nearest neutral spot. Also, when left alone, robots must be able to maneuver the ball to the opponents side of the field.
This new rule shall remove the ability of a goalie to simply block its own goal without leaving the goalie area.
> Add rule regarding ball play on the nearest neutral spot

- rules.adoc
- superteam_rules.adoc
Just a note mentioning the goals should not contain the wedge in order to allow ball passing inside smoothly.
Last world RCJ all goals were mounted on top of the wedge, so it was probably not very clear.
> Note that the goal should not contain the wedge

- rules.adoc
Adding hint about rubrics and non-gameplay categories to be merged before release of final rules
As the final rules PDF is a document that gets not only linked to but also downloaded, forwarded, printed, reuploaded to regional tournament websites including the link now should help spread awareness of the judged categories.
> Add hint about rubrics and their importance

- rules.adoc
Increasing the kick power limit for both Lightweight and Open League to slightly more than the current Open League Limit. Note that this will be subject to real testing in the coming weeks and may be changed.
The new on-field kick power test on some materials resulted in less kick power for Lightweight League. Creating a unified power limit would also ease complexity of rule & testing procedure
> Increasing & unifying kick power limit

- .github/workflows/build.yml
- .gitmodules
- preamble.tex
- rules.adoc
Add the Global Rules as a submodule of its repository (https://github.com/robocup-junior/general-rules) and include it in the rule text (via the `include` command).
To make sure the General Rules are included inside the text of the soccer rules.
> 2025 soccer draft rules global rules

- rules.adoc
- superteam_rules.adoc
As we spoke about in the meeting this adds contact email and discord in an info-box at the top of the rules
See meeting notes
> Add community discord and email reachability to rules doc

- rules.adoc
Removing the 2200g weight limit on open league
An increase of the weight limit of OL has been discussed at RCJ 2024 in Eindhoven as well as [on the forum](https://junior.forum.robocup.org/t/higher-soccer-open-weight-limit-proposal/3958/5) but we had not gone forward with it because the weight of OL robots was far away from 2200g. Teams have asked again because they now have concrete designs that the weight limit would be a problem for. So after discussing wether this would cause any issues we came to the conclusion that the risk is low enough that we can enable whatever new design that might be forthcoming because most teams are already not constrained by the limit (In Eindhoven the average robot weight was ~600g below the limit).
> open league remove weight limit

- rules.adoc
Removed "construction and programming to be performed by teams" from soccer rules.
Also contains some typo, phrasing fixes where I was made aware of small issues.
> Remove another section moved to general rules
