- .ci/build.sh
- tex/sample.tex
* Add a new line to `sample.tex`
> update: Add a line to `sample.tex`

- .ci/build.sh
- tex/sample.tex
> update: ANother change

- .ci/build.sh
- tex/sample.tex
* Removed a comma from the end of a line in `sample.tex`
> update: Removed a comma

- .ci/build.sh
- .ci/travis_bot.py
- tex/sample.tex
> update: A small test change

- tex/rules.tex
Update number of team members for 2018
To be consistent with other RoboCupJunior leagues
cc @gngrbrdmn
> update: Number of team members for 2018

- tex/rules.tex
> Change 3 ->2 sub-leagues

- tex/rules.tex
* Small updates in the regulations section.
* Small updates necessary for 2018.
> regulations: Small updates

- tex/rules.tex
*  A coupe of small updates on the floor and robot causing damage
* Removed part on carpet quality.
* Necessary changes for situations when robot repeatedly causes damage.
> small-changes: A coupe of small updates on the floor and robot causing damage

- tex/rules.tex
* Goalie has to approach the ball in the whole penalty area
* Robots must be constructed in a way that they do not enter the gaol.
> * Goalie has to approach the ball in the whole penalty area
This makes it easy to determine whether a goalie actually moves along all axes or not.
> * Robots must be constructed in a way that they do not enter the gaol.
Previously they could also be programmed in a way that would have prevented them from entering the goal. This has proven to be problematic.
> agility: A few updates

- tex/rules.tex
* Create International Competition section
* International Competition rules are generally logistical and can be part of a specific section.
> international-competition: Add section

- tex/rules.tex
References to three sub-leagues have been replaced with two sub-leagues.
The changes represent the state of affairs during 2018.
> update: Small changes in LEAGURE REGULATIONS

- tex/rules.tex
* Add a note on how to ensure one gets matte balls from Schweikert
* There were reports of semi-glossy balls received from Schweikert -- this should improve the situation at least a bit.
> update: Note on schweikert matte balls

- tex/rules.tex
* Add a short note on Elekit balls
* The name of the Elekit balls may change in the (near) future, although their specs should be still the same. This change makes sure that any Elekit ball gets recognized as approved.
> update: Add a short note on Elekit balls

- tex/rules.tex
* Update robot move in position.
* This change simplifies putting the robot into play to a great extend.
> update: Robot move in position

- tex/rules.tex
* Robots removed from play need to be turned off
* Handle needs to be visible and reachable from around 22 cm
* Add a few tollerances
Most of these are small updates that improve gameplay, transparency and simplify building the field.
> update: Various small updates

- tex/rules.tex
* No visible interfering light
* Robots which emit a lot of visible light prevent other robots from using cameras -- this should help regulate such situations.
> update: No visible interfering light

- rules.adoc
* Add a recommendation to use a brighter shade of blue, so as to make
sure it is different enough from the back paint used on the exterior.
https://junior.forum.robocup.org/t/rule-change-suggestion-color-of-goals/1010
> update: Add a note on brighter blue

- rules.adoc
* Introduce penalty kick as a standard response to multiple defense,
which is a much bigger offense with the goalie getting higher priority.
https://junior.forum.robocup.org/t/suggestion-for-future-rules/985/7?u=mareksuppa
> multiple-defense: Introduce penalty kick

- rules.adoc
* Decrease robot size in open to 20cm in 2020 and 2021.
* Ensure the proportion between the goal width and the width of the robot gets closer to the situation in FIFA Soccer.
> open: Decrease robot size

- rules.adoc
* Decrease the size of penalty area from 90 cm to 70 cm so that the
goalie's advantage is a bit more balanced.
* Make sure the attacking robots can move along all the axis of the field (especially near the corners) without being in violation of the rules.
> penalty-area: Decrease size from 90 to 70 cm

- rules.adoc
* Remove a rule on penalty area that has been made redundant by the new
changes.
https://github.com/RoboCupJuniorTC/soccer-rules/pull/50#issuecomment-500184384
> penalty-area: Remove redundant rule

- rules.adoc
* Move everything kick-off related to the kick-off section.
* Add a section on the neutral kick-off.
* Reflow of various paragraphs.
- To ensure everything kick-off related can be found in the same place.
- To fix the issue with just "out of bounds" robots penalties being discarded.
> fix: Small clarity updates

- .gitignore
Created .gitignore to not accidentally check in build output
To avoid 'contaminated' commits
> Added .gitignore to ignore render output

- rules.adoc
* Ensure the 2023 rules do not include the provision for limiting the voltage to 9V.
- The change has proved to be both difficult to implement well as well as rather unpopular
> update: Get rid of the 9V intentions for 2023

- rules.adoc
Specify the golf ball to be matte and not have a soft-touch finish.
Standardise golf ball to be used at tournaments.
> specify golf ball to be matte & not soft-touch

- rules.adoc
Reducing the out-of-bounds area to 10 cm in width and moving the neutral spots a little.
To make the match run more smoothly and reduce the lack-of-progress situations due to balls resting outside the field.
> DRAFT: specify new field line dimensions, schematics are still missing.

- rules.adoc
Some events are restricted to using a lighter carpet.
Teams should be prepared for that.
> Updated language on carpet shade

- rules.adoc
This just includes the uncontroversial part of the phrasing.
I manually copied over parts of @MikeRCJ s PR which has gotten muddled with the carpet clarification
> Clarified how IR devices are not permissible, greatest common denominator edition

- .github/workflows/build.yml
- rules.adoc
- superteam_rules.adoc
Pulled relevant changes forward and extended build-script to also build and publish superteam rules
Pulled relevant changes forward and extended build-script to also build and publish superteam rules
> Superteam rules adapted for 2023

- rules.adoc
Changed Light Weight League to on-field measurement procedure
As discussed on the forum:
https://junior.forum.robocup.org/t/increasd-kicker-power-limit-for-light-weight-league-soccer-rules-2024/3297
> Changed Light Weight League to on-field measurement procedure

- rules.adoc
Increased LWL weight limit
For reasons outlined in the discussion on the forum:
https://junior.forum.robocup.org/t/weight-limit-in-lwl-soccer-rules-2024/3299
> increase LWL weight limit to 1400g

- rules.adoc
Added AC voltage limit specification to 25V RMS such that students are not over the common limit for countries.
> Inclusion of AC voltage limits

- preamble.tex
Updated committee members and roles - please check I didn't slip up with these
To be up to date with current committee for final release
> Update to 2024 committee members

- preamble.tex
- rules.adoc
- superteam_rules.adoc
Removed all references to the rules being draft rules
Fortunately no significant changes were needed from what we put out as a draft after community feedback.
> Release rules as final

- rules.adoc
Removed Team participation limit in Lightweight League.
This rule affects a very small number of teams and has negatively impacted multiple teams from smaller regions in past.
> Removed participation limit in LWL

- rules.adoc
* Porting small changes from https://github.com/robocup-junior/soccer-rules/pull/100
There were small changes in https://github.com/robocup-junior/soccer-rules/pull/100 which were never implemented. This Commit tries to make sure they do get implemented.
It would be great if we manage to close https://github.com/robocup-junior/soccer-rules/pull/100 at some point
> chore: Small changes

- rules.adoc
Updated links from draft branch location to master branch location.
Updated links from draft branch location to master branch location.
> Updated links from draft branch location to master branch location.

- rules.adoc
* Clarify that the links to ball and field specifications are in the footnote.
* To make sure we don't confuse people reading the rules from top to bottom (the `here` was a bit confusing).
> update: Clarify footnote comment
